config/routes.rb
Rails.application.routes.draw do

 devise_for :users,skip: [:passwords], controllers: {
 registrations: "public/registrations",
 sessions: 'public/sessions'
 }
 devise_scope :user do
    post '/users/guest_sign_in', to: 'public/sessions#new_guest'
 end

    root to: "public/homes#top"
    get "/about" => "homes#about", as: "about"
    get '/users/mypage' => 'public/users#mypage', as: 'mypage'
    get '/users/bookmark' => 'public/posts#bookmark', as: 'bookmark'
    get "/users/unsubscribe" => "public/users#unsubscribe", as: "unsubscribe"
    patch '/users/:id/withdraw' => 'public/users#withdraw', as: "withdraw"

 scope module: :public do
    resources :users, only: [:edit, :update, :show]
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
        resources :comments, only: [:create, :destroy]
        resource :favorites, only: [:create, :destroy]
    end
 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
 sessions: "admin/sessions"
}

namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :categories, only:[:index, :create, :edit, :update, :destroy]
    resources :users, only:[:index, :edit, :update, :show]
    resources :posts, only:[ :show, :edit, :update, :destroy, :index]  do
        resources :comments, only:[ :destroy]
    end
end

end

app/models/post.rb
class Post < ApplicationRecord
is_impressionable  #アクセスランキング用
has_one_attached :image

validates :category_id, presence: true
validates :title, presence: true, length: { maximum: 255 }
validates :outline, presence: true
validates :necessaries, presence: true, length: { maximum: 255 }
validates :point, presence: true
validates :procedures, presence: true

enum status: { public: 0, private: 1 }, _prefix: true #記事の公開・非公開用

belongs_to :user
belongs_to :category
has_many :post_tag_relations, dependent: :destroy
has_many :tags, through: :post_tag_relations, dependent: :destroy
has_many :comments, dependent: :destroy
has_many :favorites, dependent: :destroy
has_many :procedures, dependent: :destroy
has_many :impressions, foreign_key: :impressionable_id
accepts_nested_attributes_for :procedures, allow_destroy: true,reject_if: :content_present?

def content_present?(attributes) #手順
    if attributes[:id].present?
      Procedure.find(attributes[:id]).destroy if attributes[:content] == nil
    end
end

def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
end

def favorited_by?(user) #いいね機能
  favorites.exists?(user_id: user)
end

def self.search(search) #検索機能
  Post.where(['title LIKE ?', "%#{search}%"])
end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
 before_action :authenticate_admin!

  def index
    if params[:tag_ids]
      tag_ids=[]
      params[:tag_ids].each do |key, value|
        tag_ids += Tag.where(name: key).pluck(:id) if value == "1"
      end
      @posts = Post.joins(:tags).where(status: "public").where(tags:{id: tag_ids}).distinct.page(params[:page])
    elsif params[:search].present?
      @posts = Post.where(status: "public").search(params[:search]).order(created_at: :desc)
      @posts = Kaminari.paginate_array(@posts).page(params[:page])
    elsif params[:category_id].present?
      @category = Category.find(params[:category_id])
      @posts = @category.posts.where(status: "public").order(created_at: :desc)
      @posts = Kaminari.paginate_array(@posts).page(params[:page])
    else
      @posts = Post.where(status: "public").all.order(created_at: :desc).page(params[:page])
    end
    @tags = Tag.all
    @categories = Category.all
  end


  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @user = @post.user
    @categories = Category.all
  end

  def edit
    @post = Post.find(params[:id])
    unless
      @post.user == current_user || admin_signed_in?
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = '更新しました'
      redirect_to admin_post_path(@post.id)
    else
      @posts = Post.all
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_top_path
  end

  private

  def post_params
    params.require(:post).permit(:category_id, :title, :outline, :necessaries, :image, :point, :status, tag_ids: [], procedures_attributes: [:content, :post_id, :id, :_destroy])
  end

end

app/views/admin/posts/_list.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">

      <div class="pt-2 pb-2 pl-3 pr-2">
      <h5 class="pb-1">カテゴリ検索</h5>
      <% categories.each do |category| %>
      <td>
        <%= link_to category.category_name, admin_posts_path(category_id: category.id), class: "text-secondary" %>
      </td><br>
      <% end %>
      <br><br>
      <h5 class="pb-1">タグ検索</h5>
      <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
        <% Tag.all.each do |t| %>
          <label class="label">
            <li class="tag_list"><%= check_box :tag_ids, t.name %><%= t.name %></li>
          </label>
        <% end %>
        <%= submit_tag '検索' %>
      <% end %>
      </div>
    </div>

app/views/admin/posts/edit.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      入力エラーが <%= pluralize(@post.errors.count, "件ありました") %>.
    </div>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li class="nav-link"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-2">

    <%= form_with model: @post, url: admin_post_path(@post), method: :patch do |post| %>
      <table>
        <tr>
          <td class="pt-2">写真(任意)</td>
          <td class="pt-2"><%= post.file_field :image, accept: "image/*" %></td>
        </tr>
         <tr>
          <td class="pt-2">タイトル</td>
          <td class="pt-2"><%= post.text_field :title ,:size=>"70" %></td>
        </tr>
        <tr>
          <td class="pt-2">カテゴリ</td>
          <td class="pt-2"><%= post.collection_select :category_id, Category.all, :id, :category_name, include_blank: '--選択してください--' %></td>
        </tr>
        <tr>
          <td class="pt-2">概要</td>
          <td class="pt-2"><%= post.text_area :outline, :size=>"70x5",:placeholder=>"概要を書いてください" %></td>
        </tr>
        <tr>
          <td class="pt-2">必要なもの<br>(255文字まで)</td>
          <td class="pt-2"><%= post.text_area:necessaries, :size=>"70x3" %></td>
        </tr>
        <tr>
          <td class="pt-2">ポイント</td>
          <td class="pt-2"><%= post.text_area :point, :size=>"70x3" %></td>
        </tr>
        <tr>
          <td class="pt-2">タグ</td>
          <td>
            <%= post.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check pr-3'>
                <%= tag.label class: 'form-check-label' do %>
                  <%= tag.check_box class: 'form-check-input' %>
                  <%= tag.text %>
                <% end %>
            </div>
            <% end %>
          </td>
        </tr>
      </table>

      <div id="post_procedures_forms">
        <%= post.fields_for :procedures do | b | %>
        <div class="post_procedures_forms">
          <span class='label'>手順</span>
          <span class='form'><%= b.text_area :content,:size=>"70x2" %></span>
        </div>
        <% end %>
      </div>
      <div id="form_append_button">＋手順を追加する</div>
    </div>
  </div>

  <div class="row">
    <div class="mx-auto pb-5">
      <%= post.label(:public, for: nil, class:'post-status__label') do %>
        <%= post.radio_button :status, :public %>
        <%= Post.statuses_i18n[:public] %>
      <% end %>
      <span class="pl-5">
      <%= post.label(:private, for: nil, class:'post-status__label') do %>
        <%= post.radio_button :status, :private %>
        <%= Post.statuses_i18n[:private] %>
      <% end %> <br>
      </span> <br>

      <%= post.submit "内容を保存する", class:"btn btn-success btn-lg" %>
      <% end %>

      </div>

    </div>
  </div>
</div>

<div id="extend_form">
  <div class="post_procedures_forms">
    <span class='label'>手順</span><span class='form'><input type="text" name="" id=""></span>
    <span class="close_button">&times;</span>
  </div>
</div>

<style>
  #extend_form {
    display: none;
  }
</style>

<script>
  const button = document.getElementById('form_append_button')

  button.addEventListener('click', e => {
  const forms = document.getElementById('post_procedures_forms')
  const targetForms = forms.querySelectorAll('.post_procedures_forms')
  const lastForm = targetForms[targetForms.length - 1]
  console.log(lastForm)
  const lastID = lastForm.getElementsByClassName('form')[0].firstElementChild.getAttribute('id')
  //const lastID = lastForm.getAttribute('id');
  const count = parseInt(lastID.replace('post_procedures_attributes_', '').replace('_content', ''), 10) + 1;
  const extend_form = document.getElementById('extend_form').firstElementChild.cloneNode(true)
  extend_form.querySelector('span:nth-child(2) input').setAttribute('id', `post_procedures_attributes_${count}_content`)
  extend_form.querySelector('span:nth-child(2) input').setAttribute('name', `post[procedures_attributes][${count}][content]`)
  forms.append(extend_form)
  extend_form.lastElementChild.addEventListener('click', e => {
    extend_form.remove();
  });
});
let forms = document.querySelectorAll("#post_procedures_forms .post_procedures_forms")
for(var i = 0; i < forms.length; i++){
  if (i != 0) {
    const form = forms[i]
    console.log(form.nextElementSibling)
    const target = form.querySelector('span:last-child')
    const span = document.createElement('span')
    span.setAttribute('class', 'close_button')
    span.textContent = "ｘ"
    form.append(span);
    form.addEventListener('click', e => {
      form.remove();
    });
  }
}

</script>

app/views/admin/posts/index.html.erb
<%= render 'admin/posts/list', categories: @categories, tag_lists: @tag_lists,  tags: @tags%>

    <div class="col-md-9 offset-1 ">

      <% @posts.each do |post| %>
      <div class="d-flex border-bottom pl-3 pr-4" >
        <div class="mt-1 mb-3">
        <table>
          <tr>
            <td>
              <%#= image_tag post.get_image(100,100) %>
              <%= link_to admin_post_path(post),class: "text-primary font-weight-bold" do %>
                <% if post.image.attached? %>
                  <%= image_tag post.image, class: "thumbnail-index" %>
                <% else %>
                  <%= image_tag 'no_image.jpg', class: "thumbnail-index" %>
                <% end %>
              <% end %>
            </td>
            <td class="pl-4">
              <%= link_to admin_post_path(post),class: "text-primary font-weight-bold" do %>
                <span class="post-title font-weight-bold"><%= post.title.truncate(30) %><br></span>
              <% end %>
              <%= post.outline.truncate(60) %><br><br>
              <span class="pr-3"><%= post.created_at.strftime('%Y/%m/%d') %></span>
              <%= link_to "♡#{post.favorites.count}", admin_post_path(post.id),class: "text-danger pr-3" %>
              <i class="fas fa-comment-dots"></i><%= link_to post.comments.count, admin_post_path(post.id),class: "text-dark pr-3" %>
            </td>
          </tr>
        </table>
        </div>
      </div><br>
      <% end %>
      <div class="offset-4 pb-5">
        <%= paginate @posts %>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<%= render 'admin/posts/list', categories: @categories,  tags: @tags%>

   <div class="col-md-9 offset-1">
    <div class="border pb-3">
      <div class="p-5">
        <% if current_user== @post.user %>
          <%= link_to "編集する", edit_post_path(@post),class:"btn btn-success", data: {"turbolinks" => false} %>
          <%= link_to "削除する", post_path(@post),class:"btn btn-danger", method: :delete, "data-confirm" => "本当に消しますか?" %>
        <% elsif admin_signed_in? %>
          <%= link_to "管理者用編集", edit_admin_post_path(@post),class:"btn btn-success", data: {"turbolinks" => false} %>
          <%= link_to "管理者削除", admin_post_path(@post),class:"btn btn-danger", method: :delete, "data-confirm" => "本当に消しますか?" %>
        <% end %>
        <br><br>

        <% @post.impressionist_count %>

        <span style="font-size:25px">
          <%= @post.title %>
        </span>
        <%= link_to admin_user_path(@user), class: "text-secondary" do %><br>
          <i class="fas fa-pen"></i>️<%= @post.user.nickname %>
        <% end %><br><br>

        <% if @post.image.attached? %>
          <%= image_tag @post.image, class: "thumbnail" %>
        <% else %>
          <%= image_tag 'no_image.jpg', class: "thumbnail-default" %>
        <% end %> <br><br>
        
        <div class="pt-3">
          投稿日：<%= @post.created_at.strftime('%Y/%m/%d') %>
        </div>

        <div class="pb-3 pt-3 w-100">
        　<div class="pt-1 pb-3">
          　<%= @post.outline  %>
        　</div>

        　<p>【必要なもの】</p>
          <p><%= @post.necessaries %></p>
        　<p><i class="fas fa-hand-point-up"></i>ポイント</p>
          <p><%= @post.point %></p>

　        <p>【手順】</p>
          <p>
            <% @post.procedures.each do |procedure| %>
            <%= procedure.content %><br>
            <% end %>
          </p>
          
          <div class="pt-3">
            <% @post.tags.each do |tag| %>
            <div class="btn btn-secondary">
              <span>#<%= tag.name %></span>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="offset-1 pt-3 pb-5">
      <div class="pt-4 pb-5">
        【コメント】　件数：<%= @post.comments.count %>

        <% @post.comments.each do |comment| %>
          <div class="rounded border-bottom w-75 pr-4 pt-3">
            <div class="text-right text-secondary"><%= comment.created_at.strftime('%Y/%m/%d') %></div>
            <%= link_to link_to(comment.user.nickname, user_path(comment.user_id)), class: "text-secondary" %>
            <br>
            <%= comment.comment %>
            <% if current_user == comment.user %>
              <%= link_to "削除", post_comment_path(comment.post, comment), method: :delete %>
            <% elsif admin_signed_in? %>
              <%= link_to "管理者用削除", admin_post_comment_path(comment.post, comment), method: :delete, "data-confirm" => "本当に消しますか?" %>
            <% end %><br>
          </div>
        <% end %>

        </div>
      </div>
    </div>
  </div>
</div>