config/routes.rb
Rails.application.routes.draw do

 devise_for :users,skip: [:passwords], controllers: {
 registrations: "public/registrations",
 sessions: 'public/sessions'
 }
 devise_scope :user do
    post '/users/guest_sign_in', to: 'public/sessions#new_guest'
 end

    root to: "public/homes#top"
    get "/about" => "homes#about", as: "about"
    get '/users/mypage' => 'public/users#mypage', as: 'mypage'
    get '/users/bookmark' => 'public/posts#bookmark', as: 'bookmark'
    get "/users/unsubscribe" => "public/users#unsubscribe", as: "unsubscribe"
    patch '/users/:id/withdraw' => 'public/users#withdraw', as: "withdraw"

 scope module: :public do
    resources :users, only: [:edit, :update, :show]
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
        resources :comments, only: [:create, :destroy]
        resource :favorites, only: [:create, :destroy]
    end
 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
 sessions: "admin/sessions"
}

namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :categories, only:[:index, :create, :edit, :update, :destroy]
    resources :users, only:[:index, :edit, :update, :show]
    resources :posts, only:[ :show, :edit, :update, :destroy, :index]  do
        resources :comments, only:[ :destroy]
    end
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :nickname, :name_kana, :email,
    length: { maximum: 255 }
  validates :nickname,presence: true
  validates :name_kana,presence: true, 
  format: {
    with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
    message: "全角カタカナのみで入力して下さい"
  }
  validates :email,presence: true
  validates :area,presence: true
  VALID_PASSWORD_REGEX = /\A[a-z0-9]+\z/i
  validates :password, format: { with: VALID_PASSWORD_REGEX }


  def self.guest
    find_or_create_by(email: 'guest@example.com' ) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "クマ"
      user.name_kana = "クマ"
      user.area = 1
    end
  end

  enum area: { "北海道": 0, "東北": 1, "関東": 2, "中部": 3, "近畿": 4, "中国": 5, "四国": 6, "九州": 7,"沖縄": 8 }

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
 before_action :authenticate_admin!

def index
  @users = User.all.page(params[:page])
end

def show
  @user = User.find(params[:id])
  @posts = @user.posts.page(params[:page])
end

def edit
  @user = User.find(params[:id])
end

def update
  @user = User.find(params[:id])
  if @user.update(user_params)
    redirect_to admin_user_path(@user)
  else
    @users = User.all
    render:edit
  end
end

private

  def user_params
    if params[:user]
      params[:user][:area] = params[:user][:area].to_i
    end
    params.require(:user).permit(:nickname, :name_kana, :area, :email, :is_active)
  end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-sm-12 pb-5">
      <h4 class="pb-4"><%=@user.nickname %>さんの会員情報</h4>

      <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
      <table>
        <tr><td width="200" class="pb-2"><%= f.label :"会員ID" %></td><td><%= @user.id %></td></tr>
        <tr><td class="pb-2"><%= f.label :"ニックネーム" %></td><td class="pb-2"><%= f.text_field :nickname %></td></tr>
        <tr><td class="pb-2"><%= f.label :"氏名ガナ" %></td><td class="pb-2"><%= f.text_field :name_kana %></td></tr>
        <tr><td class="pb-2"><%= f.label :"エリア" %></td><td class="pb-2"><%= f.select :area, User.areas, {}, {class: 'area'} %></td></tr>
        <tr><td class="pb-3"><%= f.label :"メールアドレス" %></td><td class="pb-3"><%= f.text_field :email %></td></tr>
        <tr><td class="pb-2"><%= f.label :"会員ステータス"%></td>
          <td  class="pb-2">
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "有効" %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "退会" %><br>
          </td>
        <tr class="pt-4"><td>　</td><td class="pt-4"><%= f.submit "変更を保存" ,class:"btn btn-success btn-lg" %></td></tr>
      </table>
    </div>

  <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 pt-5 pb-5">
      <table class="table table-hover table-inverse">
        <tr>
          <th>会員ID</th>
          <th>ニックネーム</th>
          <th>氏名(カナ)</th>
          <th>ステータス</th>
        </tr>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td>
            <%= link_to admin_user_path(user) do %>
              <%= user.nickname %>
            <% end %>
          </td>
          <td><%= user.name_kana %></td>
          <td>
            <% if user.is_active == true %>
              <%= "有効" %>
            <% else %>
              <%= "退会" %>
            <% end %>
            </td>
        <% end %>
      </table>
      <div class="offset-5"><%= paginate @users %></div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-4 pt-5 pb-5">
      <h5 class="pb-1 font-weight-bold">
        登録情報
        <%= link_to "編集する", edit_admin_user_path,class:"btn btn-success" %>
      </h5>
      <table class="table table-bordered">
        <tr>
          <td class="table-secondary w-25">ユーザーID</td>
          <td class="W-25"><%= @user.id %></td>
        </tr>
        <tr>
          <td class="table-secondary w-25">ニックネーム</td>
          <td class="w-25"><%= @user.nickname %></td>
        </tr>
        <tr>
          <td class="table-secondary">氏名カナ</td>
          <td><%= @user.name_kana %></td>
        </tr>
        <tr>
          <td class="table-secondary">エリア</td>
          <td><%= @user.area %></td>
        </tr>
        <tr>
          <td class="table-secondary">メールアドレス</td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td class="table-secondary" width="200">会員ステータス</td>
          <td class="pb-3">
            <% if @user.is_active == true %>
            <%= "有効" %>
            <% else %>
            <%= "退会" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>

    <div class="col-md-8 pt-5 pb-5">
      <div class="pl-5"><br><br>
      <% @posts.each do |post| %>
      <div class="d-flex border-bottom pl-3 pr-3">
        <div class="mb-1">
          <table>
            <tr>
              <td class="pb-3">
                <%= link_to admin_post_path(post),class: "text-primary font-weight-bold" do %>
                  <% if post.image.attached? %>
                    <%= image_tag post.image, class: "thumbnail-index" %>
                  <% else %>
                    <%= image_tag 'no_image.jpg', class: "thumbnail-index" %>
                  <% end %>
                <% end %>
              </td>
              <td class="pl-4">
                <%= link_to admin_post_path(post) do %>
                  <span class="post-title font-weight-bold">
                    <%= post.title %>
                  </span>
                <% end %> <br>
                <%= post.outline.truncate(60) %> <br><br>
                <span class="pr-3">
                  <%= post.created_at.strftime('%Y/%m/%d') %>
                </span>
                <%= link_to "♡#{post.favorites.count}", admin_post_path(post.id),class: "text-danger pr-3" %>
                <i class="fas fa-comment-dots"></i><%= link_to post.comments.count, admin_post_path(post.id),class: "text-dark pr-3" %>
              </td>
            </tr>
          </table>
        </div>
      </div> <br>
      <% end %>
      <div class="offset-4 pb-5">
        <div><%= paginate @posts %></div>
      </div>
      
      </div>
    </div>
  </div>
</div>