config/routes.rb
Rails.application.routes.draw do

 devise_for :users,skip: [:passwords], controllers: {
 registrations: "public/registrations",
 sessions: 'public/sessions'
 }
 devise_scope :user do
    post '/users/guest_sign_in', to: 'public/sessions#new_guest'
 end

    root to: "public/homes#top"
    get "/about" => "homes#about", as: "about"
    get '/users/mypage' => 'public/users#mypage', as: 'mypage'
    get '/users/bookmark' => 'public/posts#bookmark', as: 'bookmark'
    get "/users/unsubscribe" => "public/users#unsubscribe", as: "unsubscribe"
    patch '/users/:id/withdraw' => 'public/users#withdraw', as: "withdraw"

 scope module: :public do
    resources :users, only: [:edit, :update, :show]
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
        resources :comments, only: [:create, :destroy]
        resource :favorites, only: [:create, :destroy]
    end
 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
 sessions: "admin/sessions"
}

namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    resources :categories, only:[:index, :create, :edit, :update, :destroy]
    resources :users, only:[:index, :edit, :update, :show]
    resources :posts, only:[ :show, :edit, :update, :destroy, :index]  do
        resources :comments, only:[ :destroy]
    end
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kokokite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300&display=swap" rel="stylesheet">

  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light p-4">
      <div class="container">

      <% if admin_signed_in? %>
        <a class="navbar-brand" href="/admin/posts">
        <span class="pl-2 pr-2 pt-2 pb-2 text-dark rogo">
          <span class="logo-icon"><%= image_tag 'logo.jpg' %></span>
          ココキテ
        </span>
        </a>
      <% else %>
        <a class="navbar-brand" href="/">
          <span class="pl-2 pr-4 pt-2 pb-2 text-dark rogo">
            <span class="logo-icon"><%= image_tag 'logo.jpg' %></span>
            ココキテ
          </span>
        </a>
         <div class="pl-4">
      <%= form_tag posts_path, :method => 'get' do %>
        <p class="pt-3">
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "検索", :title => nil %>
        </p>
      <% end %>
      </div>
      <% end %>



      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <% if user_signed_in? %>
          <li>
            <%= link_to mypage_path,class:"nav-link text-dark ml-5 " do %>
              <i class="fas fa-user"></i>
              マイページ
            <% end %>
          </li>
          <li>
            <%= link_to new_post_path,class:"nav-link text-dark ml-3 ", data: {"turbolinks" => false} do %>
            <i class="fas fa-pen"></i>
              投稿
              <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-dark ml-3" do %>
            <i class="fas fa-sign-out-alt"></i>
              ログアウト
            <% end %>
          <li>

        <% elsif admin_signed_in? %>
          <li>
            <%= link_to admin_categories_path,class:"nav-link text-dark" do %>
              カテゴリ一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_posts_path,class:"nav-link text-dark ml-3" do %>
              <i class="fas fa-pen"></i>
              投稿一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_users_path,class:"nav-link text-dark ml-3" do %>
            <i class="fas fa-user"></i>
              会員一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class:"nav-link text-dark ml-3" do %>
            <i class="fas fa-sign-out-alt"></i>
              ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_registration_path, class:"nav-link text-dark ml-5" do %>
              <i class="fas fa-user-plus"></i>
              新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class:"nav-link text-dark ml-3" do %>
              <i class="fas fa-sign-in-alt"></i>
              ログイン
            <% end %>
          </li>
          <li>
            <%= link_to users_guest_sign_in_path, method: :post, class:"nav-link text-dark" do %>
              ゲストログイン（閲覧用）
            <% end %>
          </li>
       <% end %>

      </ul>
      </div>
      </div>
      </nav>
    </header>
    <%= yield %>
  </body>

  <footer>
    <div class"copyrights">© 2022 Ayano Kumada</span>
  </footer>

</html>